### PR TITLE
Improve the styling of the select2 control to be more consistent with other inputs.

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Not perfect, but seems a bit better:

image

### CODE REVIEW

**Comment by iandees** [comment]
I wonder if we should ditch the category thing altogether and just give good examples for people to follow in a free text field.

**Comment by CloCkWeRX** [comment]
Might make a fair bit of sense - with my locale of en-GB for example its not populating anything at the moment either.

**Comment by iandees** [comment]
Yea I think the data load isn't working since the i18n merge

**Comment by ArcaneDots** [comment]
The Sabas merge included a something similar. Please update this issue based on the new layout changes.

**Comment by CloCkWeRX** [comment]
Yeah, nah. This was contributed a few years ago and not merged. So if you want this; rebase it yourselves.

**Pull request closed without merging**
