### PR TITLE
Add more wording about listing or adding a business to openstreetmap, to try and improve search results

### PR DESCRIPTION
**Pull request by CloCkWeRX**
The current onosm site ranks poorly (8/10; despite the top answers linking to it). It makes it hard to find this when talking about it to people. 

Example screenshot:
image

This change slightly improves the wording and metadata available; which will hopefully improve listings.

It would be also worth exploring additional domain names or landing pages. An alternative could also be a small adwords campaign or similar to encourage people into the right location.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
I will have to have a think about this one an i18n

Edit: Oh neat, it replaces existing DOM content on the fly.

**Comment by CloCkWeRX** [comment]
@alexandre-mbm - for a user searching in English via google for the following, onosm ranks poorly or not even on the first page of results:
 * "How do I add my business to OpenStreetMap" 
 * "how do I list my business on OpenStreetMap"
 * "how can I add business to OSM" 
 * "list business openstreetmap"

The old description doesn't actually talk about what onosm does, but what OpenStreetMap is:
"OpenStreetMap is an open, global map used by people around the world to navigate and find local businesses. It's easy and free to get on the map!"

Though its a small change, it should better describe what onosm actually does and rank a bit better for searches like that.

**Comment by iandees** [comment]
I wonder if the javascript-based internationalization stuff will be picked up by Google or if there will have to be real content in the header not generated by javascript.

**Comment by CloCkWeRX** [comment]
I've assumed that real markup is going to be indexed, at least for the basic structure of the page.

https://developers.google.com/webmasters/ajax-crawling/docs/learn-more talks about google's advice for crawling generated content, and http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157 talks about some real world results; which contradict each other slightly

**Pull request merged**
