### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by cyper85**

### CODE REVIEW

**Comment by iandees** [comment]
Thanks!

**Comment by cyper85** [comment]
I think, you have to rename the folder to "de"...

**Comment by iandees** [comment]
If you put this in the console

```
i18n.lng();
```

what does it tell you?

**Comment by cyper85** [comment]
```javascript
i18n.lng();
```

> "de"

**Comment by iandees** [comment]
Huh, interesting.

**Comment by iandees** [comment]
Renamed, thanks.

**Pull request merged**
