### PR TITLE
Added subdirectory for address addition

### LINKED ISSUE #5: Make onosm.org friendly for home addresses?
@tmcw I just discovered this great little tool.  I have an OpenTripPlanner project that uses Nominatim [here](http://opentrip.atlantaregion.com/otp-leaflet-client/) and I would really like to give users a way to add their address to OSM if it doesn't show up in their search.

Would you accept an extension to onosm.org with language that is friendly for home addresses?  Maybe the root of onosm.org could stay biz-focuses and a sub-directory `home` could be focused on adding home addresses?

Thoughts?

### PR DESCRIPTION
**Pull request by landonreed**
Fixes #5.

Originally, the goal here was to allow people to add their residences, but I've made the language generic enough so that we could be dealing with any address.

The `address` subdirectory creates a place for users to add their address to OSM if it's missing.

The `index.html` is pretty much a clone of the existing one, with form fields changed/removed.  The major tweaks in `site.js` are just to check whether we're on the original `index.html` or the new one.

I'd like to get feedback from @iandees and @tmcw about whether additional fields/tags should be added, the main one being `Category` like you have for the original onosm.org

EDIT: Here's a look at [a request to the Notes API](http://api.openstreetmap.org/api/0.6/notes?bbox=-84.828,33.316,-83.864,34.297) showing a `POST` from onosm.org running locally.

### CODE REVIEW

**Comment by iandees** [comment]
Alexandre, please feel free to create a pull request that adds support for
i18n on this repo. That would certainly make your maintenance easier!

**Comment by landonreed** [comment]
Hey @iandees, was wondering what you thought about this pr?  Functional?  Does the language need work?

Feel free to check it out live here: http://landonreed.github.io/onosm.org/address/

Thanks!

**Comment by iandees** [comment]
Just got back from my vacation and am catching up. I will take a look later today.

**Comment by alexandre-mbm** [comment]
@iandees, I'll try to find time to do this until the 30th.

**Comment by alexandre-mbm** [comment]
I did not it. I'm outta time. I didn't started it.

**Review by CloCkWeRX — APPROVED** [review]
I like it! Any chance of a merge?

**Comment by landonreed** [comment]
Haha, @CloCkWeRX.  I love that you're digging this up.

**Comment by iandees** [comment]
😄  Apologies for not ever responding here. What gave me pause is that I'd rather see the address javascript in its own file instead of checking a variable in several places to control the path.

**Comment by iandees** [comment]
If someone fixes the merge conflict with the internationalization and cleans up the boolean checks I'll merge this in!

**Comment by xuiqzy** [comment]
I like the feature! Any chance the conflicts are resolved and this will be merged soon finally? :)

**Pull request merged**
