### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by le-jun**
Added translation for the validation block and corrected small typos.

### CODE REVIEW

**Comment by iandees** [comment]
Thanks for the improvements. I skipped the spacing changes for now.

**Comment by le-jun** [comment]
Is there a reason for skipping them ?

**Comment by iandees** [comment]
Punctuation sits next to the letters and shouldn't have spaces before, only after.

**Comment by le-jun** [comment]
Even though it’s a minor issue, I have to brandish my french flag here to say that we do have some special rules regarding spacing and punctuation 😀

**Comment by iandees** [comment]
Gotcha. A web browser omits whitespace in HTML like that from display, so the spaces won't show up on the website anyway.

**Pull request merged**
